//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Advertisement')
export class AdvertisementEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  image: string;

  @Column('text', { nullable: true })
  audioUrl: string;

  @Column('text', { nullable: true })
  link: string;

  @Column('integer', { nullable: true })
  sponsorId: number;

  @Column('date', { nullable: true })
  startDate: Date;

  @Column('date', { nullable: true })
  endDate: Date;
}
