//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Editedtrack')
export class EditedtrackEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  originalTrackId: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('text', { nullable: true })
  editedFileUrl: string;

  @Column('integer', { nullable: true })
  bpm: number;

  @Column('text', { nullable: true })
  key: string;

  @Column('date', { nullable: true })
  createdAt: Date;
}
