//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Musictrack')
export class MusictrackEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  title: string;

  @Column('text', { nullable: true })
  artist: string;

  @Column('text', { nullable: true })
  album: string;

  @Column('real', { nullable: true })
  duration: number;

  @Column('text', { nullable: true })
  genre: string;

  @Column('text', { nullable: true })
  fileUrl: string;

  @Column('text', { nullable: true })
  coverImage: string;

  @Column('integer', { nullable: true })
  bpm: number;

  @Column('text', { nullable: true })
  key: string;
}
