//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Subscription')
export class SubscriptionEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('date', { nullable: true })
  startDate: Date;

  @Column('date', { nullable: true })
  endDate: Date;

  @Column('text', { nullable: true })
  status: string;

  @Column('text', { nullable: true })
  paymentMethod: string;

  @Column('real', { nullable: true })
  amount: number;
}
