//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const AdvertisementTitle = () => {
  const record = useRecordContext();
  return <span>Advertisement {record ? `"${record.title}"` : ''}</span>;
};

export const AdvertisementList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="title" />
      <ImageField source="image" />
      <UrlField source="audioUrl" />
      <UrlField source="link" />
      <ReferenceField source="sponsorId" reference="Sponsorinvestor" />
      <DateField source="startDate" />
      <DateField source="endDate" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const AdvertisementEdit = () => (
  <Edit title={<AdvertisementTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="image" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="audioUrl" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="link" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="sponsorId" reference="Sponsorinvestor" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="startDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="endDate" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const AdvertisementCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="image" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="audioUrl" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="link" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="sponsorId" reference="Sponsorinvestor" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="startDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="endDate" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="sponsorId"
    label="sponsorId"
    reference="Sponsorinvestor"
    alwaysOn
  />,
  ,
  ,
];
