//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const EditedtrackTitle = () => {
  const record = useRecordContext();
  return <span>Editedtrack {record ? `"${record.id}"` : ''}</span>;
};

export const EditedtrackList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="originalTrackId" reference="Musictrack" />
      <ReferenceField source="userId" reference="User" />
      <UrlField source="editedFileUrl" />
      <NumberField source="bpm" />
      <TextField source="key" />
      <DateField source="createdAt" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const EditedtrackEdit = () => (
  <Edit title={<EditedtrackTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="originalTrackId" reference="Musictrack" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="userId" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="editedFileUrl" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="bpm" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="key" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="createdAt" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const EditedtrackCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="originalTrackId" reference="Musictrack" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="userId" reference="User" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="editedFileUrl" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="bpm" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="key" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="createdAt" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="originalTrackId"
    label="originalTrackId"
    reference="Musictrack"
    alwaysOn
  />,
  <ReferenceInput source="userId" label="userId" reference="User" alwaysOn />,
  ,
  ,
  ,
  ,
];
