//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const MusictrackTitle = () => {
  const record = useRecordContext();
  return <span>Musictrack {record ? `"${record.title}"` : ''}</span>;
};

export const MusictrackList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="title" />
      <TextField source="artist" />
      <TextField source="album" />
      <NumberField source="duration" />
      <TextField source="genre" />
      <UrlField source="fileUrl" />
      <ImageField source="coverImage" />
      <NumberField source="bpm" />
      <TextField source="key" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const MusictrackEdit = () => (
  <Edit title={<MusictrackTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="artist" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="album" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="duration" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="genre" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="fileUrl" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="coverImage" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="bpm" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="key" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const MusictrackCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="title" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="artist" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="album" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="duration" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="genre" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="fileUrl" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="coverImage" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="bpm" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="key" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
