//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { UserList, UserCreate, UserEdit } from './resources/User';
import {
  MusictrackList,
  MusictrackCreate,
  MusictrackEdit,
} from './resources/Musictrack';
import {
  PlaylistList,
  PlaylistCreate,
  PlaylistEdit,
} from './resources/Playlist';
import {
  AdvertisementList,
  AdvertisementCreate,
  AdvertisementEdit,
} from './resources/Advertisement';
import {
  SponsorinvestorList,
  SponsorinvestorCreate,
  SponsorinvestorEdit,
} from './resources/Sponsorinvestor';
import {
  EditedtrackList,
  EditedtrackCreate,
  EditedtrackEdit,
} from './resources/Editedtrack';
import {
  SubscriptionList,
  SubscriptionCreate,
  SubscriptionEdit,
} from './resources/Subscription';
import UserIcon from '@mui/icons-material/Person';
import MusictrackIcon from '@mui/icons-material/MusicNote';
import PlaylistIcon from '@mui/icons-material/QueueMusic';
import AdvertisementIcon from '@mui/icons-material/Campaign';
import SponsorinvestorIcon from '@mui/icons-material/BusinessCenter';
import EditedtrackIcon from '@mui/icons-material/Edit';
import SubscriptionIcon from '@mui/icons-material/Subscriptions';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a30ad5fc5">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="User"
          options={{ label: 'User' }}
          list={UserList}
          create={UserCreate}
          edit={UserEdit}
          recordRepresentation="name"
          icon={UserIcon}
        />
        <Resource
          name="Musictrack"
          options={{ label: 'Music Track' }}
          list={MusictrackList}
          create={MusictrackCreate}
          edit={MusictrackEdit}
          recordRepresentation="title"
          icon={MusictrackIcon}
        />
        <Resource
          name="Playlist"
          options={{ label: 'Playlist' }}
          list={PlaylistList}
          create={PlaylistCreate}
          edit={PlaylistEdit}
          recordRepresentation="name"
          icon={PlaylistIcon}
        />
        <Resource
          name="Advertisement"
          options={{ label: 'Advertisement' }}
          list={AdvertisementList}
          create={AdvertisementCreate}
          edit={AdvertisementEdit}
          recordRepresentation="title"
          icon={AdvertisementIcon}
        />
        <Resource
          name="Sponsorinvestor"
          options={{ label: 'Sponsor Investor' }}
          list={SponsorinvestorList}
          create={SponsorinvestorCreate}
          edit={SponsorinvestorEdit}
          recordRepresentation="name"
          icon={SponsorinvestorIcon}
        />
        <Resource
          name="Editedtrack"
          options={{ label: 'Edited Track' }}
          list={EditedtrackList}
          create={EditedtrackCreate}
          edit={EditedtrackEdit}
          recordRepresentation="id"
          icon={EditedtrackIcon}
        />
        <Resource
          name="Subscription"
          options={{ label: 'Subscription' }}
          list={SubscriptionList}
          create={SubscriptionCreate}
          edit={SubscriptionEdit}
          recordRepresentation="id"
          icon={SubscriptionIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
